# -*- coding: utf-8 -*-
"""Largest number

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm3KslHKwS3xjS-fVzZ0oAHb7OB9o7Q6
"""

a = int(input("Enter a number:"))
b = int(input("Enter a number:"))
if a > b:
  print("a is larger")
else:
  print("b is larger")