# -*- coding: utf-8 -*-
"""Natural numbers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm3KslHKwS3xjS-fVzZ0oAHb7OB9o7Q6
"""

a = int(input("enter the number:"))
sum_a = a * (a+1)//2
print("The sum of first:",a,"natural number is:",sum_a)