# -*- coding: utf-8 -*-
"""Odd or even

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm3KslHKwS3xjS-fVzZ0oAHb7OB9o7Q6
"""

a = int(input("enter a number"))
if a % 2 == 0:
  print("It is an even number")
else:
  print("It is odd number")