# -*- coding: utf-8 -*-
"""Prime numbers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm3KslHKwS3xjS-fVzZ0oAHb7OB9o7Q6
"""

a = int(input("Enter a number: "))

if a > 1:
    for i in range(2, a):
        if a % i == 0:
            print("Not Prime")
            break
    else:
        print("Prime")
else:
    print("Not Prime")