# -*- coding: utf-8 -*-
"""Reverse string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm3KslHKwS3xjS-fVzZ0oAHb7OB9o7Q6
"""

n = input("enter the string")
print("Reversed sting:",n[::-1])